export const games = [
  {
    name: 'Squish',
    description: 'Platforming party game that pits players "head" to "head".',
    image: 'https://cdn.giraugh.xyz/squish',
    link: 'http://ewanb.me/squish',
    className: 'light',
  },
  {
    name: 'Galana',
    description: 'Brutal minimalist scrolling shooter for android devices.',
    image: 'https://cdn.giraugh.xyz/galana',
    link: 'https://tdos.itch.io/galana',
    className: 'light',
  },
  {
    name: 'Clink',
    description: '8-bit adventure game made in PICO-8.',
    image: 'https://cdn.giraugh.xyz/clink',
    link: 'http://ewanb.me/clink',
    className: 'light',
  },
  {
    name: 'Fish Boy',
    description: 'Endless platforming game made for Ludum Dare 39.',
    image: 'https://cdn.giraugh.xyz/fish',
    link: 'https://tdos.itch.io/fishy',
    className: 'light',
  },
  {
    name: 'Pacmascii',
    description: 'Pacman but ASCII',
    image: 'https://cdn.giraugh.xyz/pacmascii',
    link: 'https://ewanb.me/Pasmascii',
    className: 'dark',
  },
  {
    name: 'Spades',
    description: 'Space dogfighting game made in Unity',
    image: 'https://cdn.giraugh.xyz/spades',
    link: 'https://tdos.itch.io/spades',
    className: 'dark',
  },
  {
    name: 'Knight Game',
    description: 'Platforming MOBA made in GameMaker Studio.',
    image: 'https://cdn.giraugh.xyz/knight',
    link: 'https://tdos.itch.io/knight-game',
    className: 'light',
  },
  {
    name: 'Another Expert Telegram',
    description: 'Match-several game for android devices.',
    image: 'https://cdn.giraugh.xyz/expert',
    link: 'https://play.google.com/store/apps/details?id=com.tdos.anothertelegram',
    className: 'light',
  },
  {
    name: 'Growing Up',
    description: 'Gardening rhythm game made for Ludum Dare 47.',
    image: 'https://cdn.giraugh.xyz/growing-up',
    link: 'https://growingup.avrami.me/',
    className: 'light',
  },
  {
    name: 'ASCII Marcher',
    description: 'Animated 3D Scene rendered in ASCII',
    image: 'https://cdn.giraugh.xyz/ASCII-Marcher',
    link: 'https://ewanb.me/ASCII-Marcher',
    className: 'dark',
  },
]
